version: "3.8"
services:
  nginx-demo:
    image: ${{ secrets.ECR_URI }}/dailyfix/nginx-demo:latest
    ports:
      - "8080:80"
services:
  synapse:
    image: ${{ secrets.ECR_URI }}/dailyfix/synapse:latest
    restart: unless-stopped
    ports:
      - "8008:8008"
    volumes:
      - /runtime/matrix-synapse:/data
