version: "3.8"

services:

  nginx-demo:
    image: 131881833918.dkr.ecr.ap-south-1.amazonaws.com/dailyfix/nginx-demo:latest
    ports:
      - "8080:80"

  synapse:
    image: 131881833918.dkr.ecr.ap-south-1.amazonaws.com/dailyfix-synapse:latest
    restart: unless-stopped
    ports:
      - "8008:8008"
    volumes:
      - /runtime/matrix-synapse:/data
      
