name: Deploy nginx-demo

on:
  push:
    paths:
      - "services/nginx-demo/**"
# added new comment
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      - run: aws ecr get-login-password | docker login --username AWS --password-stdin ${{ secrets.ECR_URI }}


      - run: |
          docker build -t nginx-demo services/nginx-demo
          docker tag nginx-demo:latest ${{ secrets.ECR_URI }}/dailyfix/nginx-demo:latest
          docker push ${{ secrets.ECR_URI }}/dailyfix/nginx-demo:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            aws ecr get-login-password | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
            docker compose pull
            docker compose up -d


